### ISSUE TITLE
Rate limit not respected

### ISSUE THREAD

**Issue by roncli** [emmorts/lolapi#2]
I have an application that retrieves my ranked match history.  It is longer than 150 matches, so it is more than 10 pages.  I am calling the pages sequentially, and it's usually fast enough that I'm hitting the 10 request per 10 second rate limit for test accounts.  I'm creating my lol object using `lol = require("lolapi")(config.apikey, "na")` and setting the rate limit `lol.setRateLimit(9, 499);` to test to see if a lower limit would help, but I still get 429 rate limit errors occasionally.

I looked over the code and didn't see anything entirely obvious that would cause this, but wanted to bring it to your attention.

**Comment by emmorts** [comment]
Thanks for the feedback, I'll take a look into it.

**Comment by emmorts** [comment]
I wrote some tests for it today and wasn't able to reproduce it. Would you mind sharing a code snippet where limiter fails?

**Comment by roncli** [comment]
Going through my old issues... FYI I don't use this library anymore since the LoL API in general no longer suited my needs.  Plus, it looks like some related code got changed at 50da691.  I'm going to close this issue, so if anyone else runs across this, I'd just file a new request.
