### ISSUE TITLE
How do I cache to a server?

### ISSUE THREAD

**Issue by johanb99** [emmorts/lolapi#3]
I have a redis server through microsoft azure and was wondering how I would go about doing this... The hostname seems like it's not enough information for it to connect the the redis... Don't I need to include keys or something?

**Comment by johanb99** [comment]
I just took a look at using Redis with Node.js and saw that a key was included with the host... How can I do this?

**Comment by emmorts** [comment]
In case you haven't solved your problem yet, please refer to https://azure.microsoft.com/en-us/documentation/articles/cache-dotnet-how-to-use-azure-redis-cache/. I am closing this, as it doesn't really have anything to do with this project, but if you're having any problems, don't hesitate shooting me a message.
