### ISSUE TITLE
Error with getByTeamId and getEntriesByTeamId 

### ISSUE THREAD

**Issue by pitchan** [emmorts/lolapi#4]
Hi, i am facing an issue with 2 functions to get data by team id : 

I am getting a [Error: Param id must be an integer or an array of integers]
The fact is that a Team id is not an integer, here is an example of teamId : 
- TEAM-9fa508e0-3b00-11e5-9ced-c81f66dd30e5

Thanks in advance ! ;)

**Comment by emmorts** [comment]
Fixed in 0.2.5. Sorry for the delay
